// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEImgUGcvWyNwxoPn9dashFjlLariqJFc',
    appId: '1:161290789646:web:fb051dfc0d6fc077672d5f',
    messagingSenderId: '161290789646',
    projectId: 'food-recipe-app-4fc1f',
    authDomain: 'food-recipe-app-4fc1f.firebaseapp.com',
    storageBucket: 'food-recipe-app-4fc1f.firebasestorage.app',
    measurementId: 'G-EJ8DC3QXWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCn3YnlEadRFxKpKdUDe2EflxsPLQaqq8',
    appId: '1:161290789646:android:169d0df712226308672d5f',
    messagingSenderId: '161290789646',
    projectId: 'food-recipe-app-4fc1f',
    storageBucket: 'food-recipe-app-4fc1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCDtRRjpptDjzNOf8m1Mo5RwSnqMIvZVg',
    appId: '1:161290789646:ios:9119cec27418b858672d5f',
    messagingSenderId: '161290789646',
    projectId: 'food-recipe-app-4fc1f',
    storageBucket: 'food-recipe-app-4fc1f.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCDtRRjpptDjzNOf8m1Mo5RwSnqMIvZVg',
    appId: '1:161290789646:ios:9119cec27418b858672d5f',
    messagingSenderId: '161290789646',
    projectId: 'food-recipe-app-4fc1f',
    storageBucket: 'food-recipe-app-4fc1f.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEImgUGcvWyNwxoPn9dashFjlLariqJFc',
    appId: '1:161290789646:web:ff70e09e6d1301d9672d5f',
    messagingSenderId: '161290789646',
    projectId: 'food-recipe-app-4fc1f',
    authDomain: 'food-recipe-app-4fc1f.firebaseapp.com',
    storageBucket: 'food-recipe-app-4fc1f.firebasestorage.app',
    measurementId: 'G-T4KP5LLN5J',
  );
}
